CREATE DATABASE IF NOT EXISTS baume_newsletter;

CREATE TABLE mail ( 
    id_mail INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    mail VARCHAR(255) UNIQUE NOT NULL,
    date_mail DATETIME DEFAULT CURRENT_TIMESTAMP
);


